{{- if .Values.productsService.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: products-service-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.productsService.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  namespace: {{ .Values.namespace }}
  labels:
    app: products-service
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.productsService.replicaCount }}
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
      - name: products-service
        image: "{{ .Values.productsService.image.repository }}:{{ .Values.productsService.image.tag }}"
        imagePullPolicy: {{ .Values.productsService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.productsService.service.targetPort }}
        env:
        {{- range $key, $value := .Values.productsService.env }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              name: products-service-config
              key: {{ $key }}
        {{- end }}
        resources:
          {{- toYaml .Values.productsService.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health/live
            port: {{ .Values.productsService.service.targetPort }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: {{ .Values.productsService.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  selector:
    app: products-service
  ports:
  - port: {{ .Values.productsService.service.port }}
    targetPort: {{ .Values.productsService.service.targetPort }}
    protocol: TCP
  type: {{ .Values.productsService.service.type }}
{{- end }}
