apiVersion: v2
name: microservices
description: A Helm chart for microservices application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - microservices
  - kubernetes
  - nodejs
  - python
home: https://github.com/your-org/microservices
sources:
  - https://github.com/your-org/microservices
maintainers:
  - name: DevOps Team
    email: devops@company.com
