apiVersion: v1
kind: ConfigMap
metadata:
  name: products-service-config
  namespace: microservices
data:
  PORT: "5000"
  MONGO_URI: mongodb://mongodb-service:27017/
  DB_NAME: products_db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  namespace: microservices
  labels:
    app: products-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
      - name: products-service
        image: products-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: products-service-config
              key: PORT
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: products-service-config
              key: MONGO_URI
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: products-service-config
              key: DB_NAME
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: microservices
spec:
  selector:
    app: products-service
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer
