name: 🔍 Debug Docker Secrets

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: 🔍 Debug Docker Hub Secrets
      run: |
        echo "=================================================="
        echo "🔍 DEBUGGING DOCKER HUB SECRETS"
        echo "=================================================="
        echo ""
        echo "Checking if secrets are available to the workflow..."
        echo ""
        
        # Check if DOCKER_USERNAME is set (without revealing the value)
        if [ -n "$DOCKER_USERNAME" ]; then
          echo "✅ DOCKER_USERNAME environment variable is accessible"
          echo "   Length: ${#DOCKER_USERNAME} characters"
        else
          echo "❌ DOCKER_USERNAME environment variable is NOT accessible"
        fi
        
        # Check if DOCKER_PASSWORD is set (without revealing the value)
        if [ -n "$DOCKER_PASSWORD" ]; then
          echo "✅ DOCKER_PASSWORD environment variable is accessible"
          echo "   Length: ${#DOCKER_PASSWORD} characters"
        else
          echo "❌ DOCKER_PASSWORD environment variable is NOT accessible"
        fi
        
        echo ""
        echo "📋 If secrets are not accessible, please verify:"
        echo "1. Go to: https://github.com/${{ github.repository }}/settings/secrets/actions"
        echo "2. Ensure you have added:"
        echo "   - DOCKER_USERNAME = baffoe6"
        echo "   - DOCKER_PASSWORD = [your Docker Hub token]"
        echo ""
        echo "📖 Full instructions: https://github.com/${{ github.repository }}/blob/main/SETUP_CHECKLIST.txt"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  test-docker-login:
    runs-on: ubuntu-latest
    steps:
    - name: 🔐 Attempt Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      continue-on-error: true
      id: docker_login
    
    - name: 📊 Login Result
      run: |
        if [ "${{ steps.docker_login.outcome }}" == "success" ]; then
          echo "🎉 SUCCESS! Docker Hub login worked perfectly!"
          echo "Your CI/CD pipeline should now work correctly."
        else
          echo "❌ FAILED! Docker Hub login failed."
          echo ""
          echo "This means your GitHub repository secrets are not configured correctly."
          echo ""
          echo "🔧 To fix this:"
          echo "1. Go to: https://github.com/${{ github.repository }}/settings/secrets/actions"
          echo "2. Add these repository secrets:"
          echo "   Name: DOCKER_USERNAME"
          echo "   Value: baffoe6"
          echo ""
          echo "   Name: DOCKER_PASSWORD"
          echo "   Value: [your Docker Hub access token]"
          echo ""
          echo "3. Make sure you've generated a NEW Docker Hub token (the old one was exposed)"
          echo "4. Re-run this workflow to test again"
        fi
