name: 🔍 Test Docker Hub Connection

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  check-docker-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: 📋 Check Docker Hub Secrets Status
      run: |
        echo "=================================================="
        echo "🔍 DOCKER HUB SECRETS VERIFICATION"
        echo "=================================================="
        echo ""
        echo "This workflow will test if your Docker Hub secrets are properly configured."
        echo ""
        echo "Required secrets:"
        echo "• DOCKER_USERNAME (should be: baffoe6)"
        echo "• DOCKER_PASSWORD (your Docker Hub access token)"
        echo ""
        echo "If the next step fails, you need to:"
        echo "1. Go to: https://github.com/${{ github.repository }}/settings/secrets/actions"
        echo "2. Add the missing secrets as described in SETUP_CHECKLIST.txt"

  test-docker-login:
    runs-on: ubuntu-latest
    steps:
    - name: 🔐 Test Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      continue-on-error: true
    
    - name: 🎉 Login Success
      run: |
        echo "=================================================="
        echo "✅ SUCCESS! Docker Hub login working perfectly!"
        echo "=================================================="
        echo ""
        echo "Your CI/CD pipeline will now be able to:"
        echo "• Build Docker images"
        echo "• Push to Docker Hub as:"
        echo "  - baffoe6/users-service:latest"
        echo "  - baffoe6/products-service:latest"
        echo "• Run security scans with Trivy"
        echo ""
        echo "🚀 Ready to run the full CI/CD pipeline!"
