name: Test Docker Secrets

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Check if Docker secrets exist
      run: |
        echo "Checking Docker Hub secrets..."
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "❌ DOCKER_USERNAME secret is not set"
        else
          echo "✅ DOCKER_USERNAME secret is set"
        fi
        
        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "❌ DOCKER_PASSWORD secret is not set"
        else
          echo "✅ DOCKER_PASSWORD secret is set"
        fi
        
        echo ""
        echo "If both secrets are not set, please follow these steps:"
        echo "1. Go to: https://github.com/${{ github.repository }}/settings/secrets/actions"
        echo "2. Add DOCKER_USERNAME with value: baffoe6"
        echo "3. Add DOCKER_PASSWORD with your Docker Hub token"
